/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetarSenhaRouteImport } from './routes/resetar-senha'
import { Route as ProtecaoRouteImport } from './routes/protecao'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelPacientesRouteImport } from './routes/painel.pacientes'
import { Route as PainelGestaoRouteImport } from './routes/painel.gestao'
import { Route as PainelPacientesNovoRouteImport } from './routes/painel.pacientes.novo'
import { Route as PainelPacienteIdRouteImport } from './routes/painel.paciente.$id'

const ResetarSenhaRoute = ResetarSenhaRouteImport.update({
  id: '/resetar-senha',
  path: '/resetar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoRoute = ProtecaoRouteImport.update({
  id: '/protecao',
  path: '/protecao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPacientesRoute = PainelPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelGestaoRoute = PainelGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPacientesNovoRoute = PainelPacientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PainelPacientesRoute,
} as any)
const PainelPacienteIdRoute = PainelPacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/protecao': typeof ProtecaoRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/painel/gestao': typeof PainelGestaoRoute
  '/painel/pacientes': typeof PainelPacientesRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/paciente/$id': typeof PainelPacienteIdRoute
  '/painel/pacientes/novo': typeof PainelPacientesNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/protecao': typeof ProtecaoRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/painel/gestao': typeof PainelGestaoRoute
  '/painel/pacientes': typeof PainelPacientesRouteWithChildren
  '/painel': typeof PainelIndexRoute
  '/painel/paciente/$id': typeof PainelPacienteIdRoute
  '/painel/pacientes/novo': typeof PainelPacientesNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/protecao': typeof ProtecaoRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/painel/gestao': typeof PainelGestaoRoute
  '/painel/pacientes': typeof PainelPacientesRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/paciente/$id': typeof PainelPacienteIdRoute
  '/painel/pacientes/novo': typeof PainelPacientesNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/painel'
    | '/protecao'
    | '/resetar-senha'
    | '/painel/gestao'
    | '/painel/pacientes'
    | '/painel/'
    | '/painel/paciente/$id'
    | '/painel/pacientes/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/protecao'
    | '/resetar-senha'
    | '/painel/gestao'
    | '/painel/pacientes'
    | '/painel'
    | '/painel/paciente/$id'
    | '/painel/pacientes/novo'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/painel'
    | '/protecao'
    | '/resetar-senha'
    | '/painel/gestao'
    | '/painel/pacientes'
    | '/painel/'
    | '/painel/paciente/$id'
    | '/painel/pacientes/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  ProtecaoRoute: typeof ProtecaoRoute
  ResetarSenhaRoute: typeof ResetarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resetar-senha': {
      id: '/resetar-senha'
      path: '/resetar-senha'
      fullPath: '/resetar-senha'
      preLoaderRoute: typeof ResetarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao': {
      id: '/protecao'
      path: '/protecao'
      fullPath: '/protecao'
      preLoaderRoute: typeof ProtecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/pacientes': {
      id: '/painel/pacientes'
      path: '/pacientes'
      fullPath: '/painel/pacientes'
      preLoaderRoute: typeof PainelPacientesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/gestao': {
      id: '/painel/gestao'
      path: '/gestao'
      fullPath: '/painel/gestao'
      preLoaderRoute: typeof PainelGestaoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/pacientes/novo': {
      id: '/painel/pacientes/novo'
      path: '/novo'
      fullPath: '/painel/pacientes/novo'
      preLoaderRoute: typeof PainelPacientesNovoRouteImport
      parentRoute: typeof PainelPacientesRoute
    }
    '/painel/paciente/$id': {
      id: '/painel/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/painel/paciente/$id'
      preLoaderRoute: typeof PainelPacienteIdRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelPacientesRouteChildren {
  PainelPacientesNovoRoute: typeof PainelPacientesNovoRoute
}

const PainelPacientesRouteChildren: PainelPacientesRouteChildren = {
  PainelPacientesNovoRoute: PainelPacientesNovoRoute,
}

const PainelPacientesRouteWithChildren = PainelPacientesRoute._addFileChildren(
  PainelPacientesRouteChildren,
)

interface PainelRouteChildren {
  PainelGestaoRoute: typeof PainelGestaoRoute
  PainelPacientesRoute: typeof PainelPacientesRouteWithChildren
  PainelIndexRoute: typeof PainelIndexRoute
  PainelPacienteIdRoute: typeof PainelPacienteIdRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelGestaoRoute: PainelGestaoRoute,
  PainelPacientesRoute: PainelPacientesRouteWithChildren,
  PainelIndexRoute: PainelIndexRoute,
  PainelPacienteIdRoute: PainelPacienteIdRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  ProtecaoRoute: ProtecaoRoute,
  ResetarSenhaRoute: ResetarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
